image: alpine:latest

pages:
  stage: deploy
  tags:
    - mobius_shared_runner_cloud
  script:
    - mkdir public
    - cp *.html *.js *.json *.png public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
